# Learn more at <https://github.com/carlosperate/awesome-pyproject>
# Cool info <https://blog.pilosus.org/posts/2019/12/26/python-third-party-tools-configuration/>
# https://github.com/hhatto/autopep8/blob/master/README.rst#pyproject-toml
# https://python-poetry.org/docs/pyproject/
[tool.autopep8]
in-place = true
jobs = 0
max_line_length = 88
recursive = true

# https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#configuration-via-a-file
[tool.black]
#line-length = 88
color = true
safe = true
target-version = ['py311'] #'py37', 'py38',

[tool.darker]
check = true
diff = true
isort = true
lint = ["pylint", "mypy", "flake8"]
log_level = "INFO"
revision = "main"

[tool.flake8]
max-line-length = 88

# https://interrogate.readthedocs.io/en/latest/#configuration
[tool.interrogate]
color = true
generate_badge = "."
verbose = 2

[tool.mypy]
install_types = true
non_interactive = true
plugins = "numpy.typing.mypy_plugin"
show_error_codes = true
show_error_context = true
strict = true

[tool.isort]
# https://pycqa.github.io/isort/docs/configuration/options
color_output = true
profile = "black"
py_version = 310

[tool.pylama.pep8]
max_line_length = 88

[tool.pylint.MASTER]
include-naming-hint = "y"
jobs = 0
output-format = "colorized"

[tool.pyright]
# https://github.com/microsoft/pyright/blob/main/docs/configuration.md
reportMissingImports = true
reportMissingTypeStubs = false
typeCheckingMode = "strict"
tool.pyright.executionEnvironments = [
    "root = src/pyintlab",
    "pythonVersion = 3.11",
    "pythonPlatform = Linux"
]

[tool.pylint."MESSAGES CONTROL"]
disable = "duplicate-code"

[tool.pytest.ini_options]
minversion = "6.2"
addopts = ["--verbose"]

[tool.towncrier]

[tool.poetry]
name = "pyintlab"
version = "0.1.1-alpha.0"
description = "package in memoriam of intlab=Matlab Interval Laboratory"
authors = ["Ebeling, Dr. Bastian <bastian.ebeling@web.de>"]

[tool.poetry.dependencies]
python = "~3.11"
radon = "^5.0.1"
numpy = ">=1.22.0"

[tool.poetry.dev-dependencies]
black = "*"
coverage = "*"
eradicate = "*"
flake8 = "*"
git-story = "^0.1.4"
interrogate = "^1.5.0"
ufmt = "^2.0.1"
isort = "*"
mccabe = "*"
MonkeyType = "^22.2.0"
mypy = "*"
pep257 = "*"
pep8 = "*"
prospector = "^1.7.7"
pyanalyze = "^0.7.0"
pyannotate = "^1.2.0"
pycodestyle = "*"
pydocstyle = "*"
pyflakes = "*"
pylama = "*"
pylint = "*"
pyre-check = "*"
pyright = "^1.1.235"
pytest = "*"
setuptools = "^62.1.0"
types-setuptools = "*"
types-toml = "*"
vermin = "*"
vulture = "*"
autopep8 = "^1.6.0"

[tool.poetry.dev-dependencies.pytype]
version = ">=2022.4.22"
python = "~3.10"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
