# Learn more at <https://github.com/carlosperate/awesome-pyproject>
# Cool info <https://blog.pilosus.org/posts/2019/12/26/python-third-party-tools-configuration/>
# https://github.com/hhatto/autopep8/blob/master/README.rst#pyproject-toml
[tool.autopep8]
max_line_length = 88
in-place = true
recursive = true
jobs = 0

# https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#configuration-via-a-file
[tool.black]
#line-length = 88
target-version = ['py39'] #'py37', 'py38',
color = true
safe = true

[tool.darker]
revision = "main"
diff = true
check = true
isort = true
lint = ["pylint", "mypy", "flake8"]
log_level = "INFO"

[tool.flake8]
max-line-length = 88

# https://interrogate.readthedocs.io/en/latest/#configuration
[tool.interrogate]
color = true
generate_badge = "."
verbose = 2

[tool.mypy]
strict = true
show_error_codes = true
show_error_context = true
install_types = true
non_interactive = true
plugins = "numpy.typing.mypy_plugin"

[tool.isort]
# https://pycqa.github.io/isort/docs/configuration/options
py_version = 39
color_output = true
profile = "black"

[pylama.pep8]
max_line_length = 88

[tool.pylint.MASTER]
Bjobs = 0
output-format = "colorized"
include-naming-hint = "y"

[tool.pyright]
# https://github.com/microsoft/pyright/blob/main/docs/configuration.md
typeCheckingMode = "strict"
reportMissingImports = true
reportMissingTypeStubs = false
tool.pyright.executionEnvironments= [
    "root = src/pyintlab",
    "pythonVersion = 3.10",
    "pythonPlatform = Linux"
]

[tool.pylint."MESSAGES CONTROL"]
disable = "duplicate-code"

[tool.pytest.ini_options]
minversion = "6.2"
addopts = ["--verbose"]

[tool.towncrier]

[tool.poetry]
name = "pyintlab"
version = "0.1.0"
description = "package in memoriam of intlab=Matlab Interval Laboratory"
authors = ["Ebeling, Dr. Bastian <bastian.ebeling@web.de>"]

[tool.poetry.dependencies]
python = ">=3.7,<3.11"
# typing = "^3.10.0"
radon = "^5.0.1"
numpy = "^1.21.2"

[tool.poetry.dev-dependencies]
black = "*"
coverage = "*"
eradicate = "*"
flake8 = "*"
isort = "*"
mccabe = "*"
mypy = "*"
numpy = "*"
pep257 = "*"
pep8 = "*"
pycodestyle = "*"
pydocstyle = "*"
pyflakes = "*"
pylama = "*"
pylint = "*"
pyre-check = "*"
pytest = "*"
types-setuptools = "*"
types-toml = "*"
vermin ="*"
vulture = "*"
pyright = "^1.1.235"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
