name: Pylint
on: push
jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
      - name: Install poetry
        run: |
          curl -sSL https://install.python-poetry.org/ | python3 - --git https://github.com/python-poetry/poetry.git@master --force --yes
          export PATH="/root/.local/bin:$PATH"
          poetry --version
      - name: Poetry checking dependencies
        run: |
          poetry export --output requirements.txt --with dev --without-hashes
      - name: Installing apt dependencies
        run: |
          sudo apt-get install libpango1.0-dev
      - name: Installing further dependencies
        run: |
          python3 -m pip install --upgrade --requirement requirements.txt
      - name: Analysing the code with pylint
        run: |
          #pylint --jobs=0 --output-format=colorized --include-naming-hint=y `tree -fi|grep \.py$|xargs`
          #complicated and don't know if xargs needed
          pylint --jobs=0 --output-format=colorized --include-naming-hint=y src
