name: Pylint
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
      - name: Install poetry
        run: |
          #python3 -m pip install --upgrade poetry
          curl -sSL https://install.python-poetry.org/ | python3 - --git https://github.com/python-poetry/poetry.git@master --force --yes
      - name: Poetry checking dependencies
        run: |
          echo "================================================================"
          poetry -V
          poetry self update --preview
          poetry -V
          echo "================================================================"
          poetry export --output requirements.txt --with dev --without-hashes
      - name: Installing further dependencies
        run: |
          python3 -m pip install --upgrade --requirement requirements.txt
      - name: Analysing the code with pylint
        run: |
          pylint --jobs=0 --output-format=colorized --include-naming-hint=y `tree -fi|grep \.py$|xargs`
